const data = [
  {
    name: "Nisha Giri Puri",
    addedFrom: "System",
    tags: "-",
    internalId: "ID296",
    clientId: "-",
    phone: "9800000000",
    clientPortal: "Deactivitated",
    assignee: "Justin",
    followers: "Allison",
    status: "Completed",
    applications: "8",
    lastupdated: "2023-01-01",
  },
  {
    name: "Abram Press",
    addedFrom: "System",
    tags: "-",
    internalId: "ID297",
    clientId: "-",
    phone: "9800000001",
    clientPortal: "Deactivitated",
    assignee: "Miracel",
    followers: "Maria",
    status: "In Progress",
    applications: "2",
    lastupdated: "2023-09-01",
  },
  {
    name: "Rita Thapa",
    addedFrom: "System",
    tags: "-",
    internalId: "ID298",
    clientId: "-",
    phone: "9800000002",
    clientPortal: "Activated",
    assignee: "Emily",
    followers: "John",
    status: "In Progress",
    applications: "5",
    lastupdated: "2023-06-15",
  },
  {
    name: "Suresh Karki",
    addedFrom: "System",
    tags: "-",
    internalId: "ID299",
    clientId: "-",
    phone: "9800000003",
    clientPortal: "Deactivitated",
    assignee: "Robert",
    followers: "Michael",
    status: "Completed",
    applications: "10",
    lastupdated: "2023-03-20",
  },
  {
    name: "Amrita Basnet",
    addedFrom: "System",
    tags: "-",
    internalId: "ID300",
    clientId: "-",
    phone: "9800000004",
    clientPortal: "Activated",
    assignee: "Sophia",
    followers: "Olivia",
    status: "In Progress",
    applications: "4",
    lastupdated: "2023-07-10",
  },
  {
    name: "Rajesh Sharma",
    addedFrom: "System",
    tags: "-",
    internalId: "ID301",
    clientId: "-",
    phone: "9800000005",
    clientPortal: "Deactivitated",
    assignee: "David",
    followers: "Emma",
    status: "Completed",
    applications: "3",
    lastupdated: "2023-08-25",
  },
  {
    name: "Sunita Adhikari",
    addedFrom: "System",
    tags: "-",
    internalId: "ID302",
    clientId: "-",
    phone: "9800000006",
    clientPortal: "Activated",
    assignee: "William",
    followers: "Sophia",
    status: "Completed",
    applications: "6",
    lastupdated: "2023-02-28",
  },
];

export default data;
